apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: monitoring
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s

    scrape_configs:
      - job_name: 'kubernetes-apiservers'
        kubernetes_sd_configs:
          - role: apiserver
        scheme: https
        tls_config:
          ca_file: /etc/prometheus/secrets/k8s-ca/ca.crt
        relabel_configs:
          - source_labels: [__meta_kubernetes_apiserver_cluster_name]
            action: labelmap
            regex: (.+)
            target_label: cluster
      - job_name: 'kubernetes-nodes'
        kubernetes_sd_configs:
          - role: node
        relabel_configs:
          - source_labels: [__meta_kubernetes_node_name]
            action: replace
            target_label: instance
